vaadin/cdi

.travis-settings.xml
.travis.after_success.sh
.travis.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/cdi/174)

Travis build for validation and master snapshots

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/cdi/173)

Update README for a GitHub workflow

---

.travis.after_success.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/cdi/177)

Fix path issue in deploy script

---

vaadin-cdi/pom.xml
vaadin-cdi/src/test/java/com/vaadin/cdi/CDIIntegrationWithConflictingDeploymentTest.java
vaadin-cdi/src/test/java/com/vaadin/cdi/CDIIntegrationWithConflictingUIPathTest.java
vaadin-cdi/src/test/java/com/vaadin/cdi/CDIIntegrationWithCustomDeploymentTest.java
vaadin-cdi/src/test/java/com/vaadin/cdi/CDIIntegrationWithDefaultDeploymentTest.java
vaadin-cdi/src/test/java/com/vaadin/cdi/CrossInjectionTest.java
vaadin-cdi/src/test/java/com/vaadin/cdi/DeploymentTestSuiteIT.java
vaadin-cdi/src/test/java/com/vaadin/cdi/InappropriateCDIViewInDeploymentTest.java
vaadin-cdi/src/test/java/com/vaadin/cdi/InappropriateNestedServletInDeploymentTest.java
vaadin-cdi/src/test/java/com/vaadin/cdi/MultipleAccessIsolationTest.java
vaadin-cdi/src/test/java/com/vaadin/cdi/MultipleRootUIsTest.java
vaadin-cdi/src/test/java/com/vaadin/cdi/NonPassivatingBeanTest.java
vaadin-cdi/src/test/java/com/vaadin/cdi/QualifiedInjectionTest.java
vaadin-cdi/src/test/java/com/vaadin/cdi/RootViewAtContextRootTest.java
vaadin-cdi/src/test/java/com/vaadin/cdi/ScopedInstancesTest.java
vaadin-cdi/src/test/java/com/vaadin/cdi/ScopedProducerTest.java
vaadin-cdi/src/test/java/com/vaadin/cdi/shiro/ShiroTest.java

Rename tests and update dependencies to make all tests execute.
Use a recent Arquillian version and TomEE 7.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/cdi/182)

Make sure all tests are run with TomEE 7

---

.travis.before_install.sh
.travis.yml
pom.xml
vaadin-cdi/pom.xml
vaadin-cdi/src/test/java/com/vaadin/cdi/shiro/ShiroTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/cdi/185)

Update version number, dependencies etc. for Vaadin 8

---

vaadin-cdi/src/main/java/com/vaadin/cdi/NormalUIScoped.java
vaadin-cdi/src/main/java/com/vaadin/cdi/NormalViewScoped.java
vaadin-cdi/src/main/java/com/vaadin/cdi/UIScoped.java
vaadin-cdi/src/main/java/com/vaadin/cdi/ViewScoped.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/cdi/187)

Fix JavaDoc syntax for referencing annotations

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/cdi/188)

Fix Vaadin version in readme

---

vaadin-cdi/src/main/java/com/vaadin/cdi/internal/AbstractVaadinContext.java
vaadin-cdi/src/test/java/com/vaadin/cdi/DeploymentTestSuiteIT.java
vaadin-cdi/src/test/java/com/vaadin/cdi/UIDestroyTest.java
vaadin-cdi/src/test/java/com/vaadin/cdi/uis/DestroyUI.java

It's a fix for #176.
Part 1 of #184
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/cdi/193)

fix for closed UI cleanup

---

vaadin-cdi/pom.xml

Fixes #151
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/cdi/204)

Remove Class-Path from manifest

---

vaadin-cdi/src/main/java/com/vaadin/cdi/CDIView.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/cdi/211)

Some CDIView annotation cleanup

---

README.md
vaadin-cdi/README.md
vaadin-cdi/src/main/java/com/vaadin/cdi/VaadinSessionScoped.java
vaadin-cdi/src/main/java/com/vaadin/cdi/internal/UIContextualStorageManager.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/cdi/213)

Add missing since tags and update READMEs

---

pom.xml
vaadin-cdi/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/cdi/215)

Use parent POM and update version

---

vaadin-cdi/src/main/java/com/vaadin/cdi/CDINavigator.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/cdi/216)

Fix javadoc error in CDINavigator

---

README.md
vaadin-cdi/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/cdi/220)

Update readme files for 1.0.4

---

vaadin-cdi/src/main/java/com/vaadin/cdi/CDIUIProvider.java
vaadin-cdi/src/main/java/com/vaadin/cdi/CDIViewProvider.java
vaadin-cdi/src/test/java/com/vaadin/cdi/CDIUIProviderTest.java
vaadin-cdi/src/test/java/com/vaadin/cdi/CDIUIProviderViewDetectionTest.java

Improvements for https://github.com/vaadin/cdi/pull/227
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/cdi/229)

Improvements for PR #227

---

vaadin-cdi/src/main/java/com/vaadin/cdi/ViewContextStrategy.java

More improvements for #227 since it had to merge with master due to conflicts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/cdi/232)

Improved support for ! in paths

---

vaadin-cdi/pom.xml
vaadin-cdi/src/main/java/com/vaadin/cdi/CDINavigator.java
vaadin-cdi/src/main/java/com/vaadin/cdi/CDIUI.java
vaadin-cdi/src/main/java/com/vaadin/cdi/CDIUIProvider.java
vaadin-cdi/src/main/java/com/vaadin/cdi/CDIViewProvider.java
vaadin-cdi/src/main/java/com/vaadin/cdi/ViewContextStrategy.java
vaadin-cdi/src/test/java/com/vaadin/cdi/CDIUIProviderTest.java
vaadin-cdi/src/test/java/com/vaadin/cdi/CDIUIProviderViewDetectionTest.java
vaadin-cdi/src/test/java/com/vaadin/cdi/uis/PushStateSubUI.java
vaadin-cdi/src/test/java/com/vaadin/cdi/uis/PushStateUI.java

This patch fixes issues in UI detection as well as provide wildcard support for UI paths.
Fixes #202 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/cdi/227)

Improve support for PushState based navigation

---

vaadin-cdi/src/main/java/com/vaadin/cdi/internal/ContextDeployer.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/cdi/237)

#236 CDI fails to deploy with JAX-WS, JAX-RS Liberty (CDI 1.0.4)

---

vaadin-cdi/src/main/java/com/vaadin/cdi/internal/ContextDeployer.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/cdi/238)

#236 CDI fails to deploy with JAX-WS, JAX-RS Liberty (CDI Master)

---

vaadin-cdi/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/cdi/240)

Use parent POM

---

.travis.after_success.sh
.travis.yml
README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/cdi/245)

Update Readme and Travis after creating new branch for 3.0

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/cdi/250)

List branches and add-on versions in README

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/cdi/261)

Update readme for v10

---

pom.xml
vaadin-cdi-itest/pom.xml
vaadin-cdi-itest/src/test/java/com/vaadin/cdi/itest/ArchiveProvider.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/cdi/260)

Fix Flow version and dependencies

---

vaadin-cdi/README.md

Overwrite the readme with an overview of the 10.0 version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/cdi/262)

Initial readme of the addon child module for V10

---

pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/cdi/268)

Add vaadin-parent to allow JAR signing for release

---

pom.xml

needed for finally release
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/cdi/269)

Exclude test module from Release

---

vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/service/TestSystemMessagesProvider.java
vaadin-cdi-itest/src/test/java/com/vaadin/cdi/itest/ServiceTest.java

for #272
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/cdi/274)

Remove internal error notification itest

---

pom.xml

for #272
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/cdi/273)

Upgrade OWB to 1.7.5

---

pom.xml
vaadin-cdi-itest/pom.xml
vaadin-cdi/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/cdi/275)

Version bump

---

vaadin-cdi/src/main/java/com/vaadin/cdi/CdiInstantiator.java

Would be nice to immediately know what to do to gain I18N rather than having to resort to reading this project's source code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/cdi/281)

improve error message for usability

---

pom.xml
vaadin-cdi-itest/pom.xml
vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/BowerModeServlet.java
vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/CounterFilter.java
vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/instantiatorcustomize/InstantiatorAlternative.java
vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/template/TestTemplate.java
vaadin-cdi-itest/src/main/resources/frontend/test-template.html
vaadin-cdi-itest/src/test/java/com/vaadin/cdi/itest/ServiceTest.java
vaadin-cdi-itest/src/test/java/com/vaadin/cdi/itest/TemplateTest.java
vaadin-cdi/pom.xml
vaadin-cdi/src/main/java/com/vaadin/cdi/CdiInstantiator.java
vaadin-cdi/src/test/java/com/vaadin/cdi/CdiInstantiatorTest.java
vaadin-cdi/src/test/java/com/vaadin/cdi/PolymerTest.java
vaadin-cdi/src/test/java/com/vaadin/cdi/context/SessionUnderTestContext.java

Fixes #286
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/cdi/287)

Create a non-contextual instance in createComponent impl

---

vaadin-cdi-itest/src/test/java/com/vaadin/cdi/itest/ArchiveProvider.java
vaadin-cdi-itest/src/test/java/com/vaadin/cdi/itest/PushTest.java
vaadin-cdi-itest/src/test/java/com/vaadin/cdi/itest/RouteContextTest.java
vaadin-cdi-itest/src/test/java/com/vaadin/cdi/itest/TemplateTest.java
vaadin-cdi-itest/src/test/java/com/vaadin/cdi/itest/UIContextTest.java

This should fix tests for all 3 servers
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/cdi/295)

Make all tests run in production

---

vaadin-cdi/src/test/java/com/vaadin/cdi/context/SessionUnderTestContext.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/cdi/296)

Returns an empty properties as init properties from a configuration.

---

vaadin-cdi/src/test/java/com/vaadin/cdi/TestCdiVaadinServletService.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/cdi/299)

Fix unit tests for 2.1

---

pom.xml
vaadin-cdi-itest/pom.xml
vaadin-cdi/pom.xml
vaadin-cdi/src/test/java/com/vaadin/cdi/TestCdiVaadinServletService.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/cdi/298)

Bump project and Flow version

---

README.md
pom.xml
vaadin-cdi-itest/pom.xml
vaadin-cdi/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/cdi/300)

Updated Flow to 2.2

---

vaadin-cdi/src/main/java/com/vaadin/cdi/CdiVaadinServlet.java
vaadin-cdi/src/main/java/com/vaadin/cdi/CdiVaadinServletService.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/cdi/304)

Make CdiVaadinServiceDelegate serializable

---

vaadin-cdi/src/main/java/com/vaadin/cdi/AbstractCdiInstantiator.java
vaadin-cdi/src/test/java/com/vaadin/cdi/CdiInstantiatorTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/cdi/307)

Add usage statistics

---

vaadin-cdi/src/test/java/com/vaadin/cdi/TestCdiVaadinServletService.java
vaadin-cdi/src/test/java/com/vaadin/cdi/context/SessionUnderTestContext.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/cdi/311)

11.0 cherry picks [DO NOT Squash]

---

pom.xml
vaadin-cdi-itest/pom.xml
vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/service/BootstrapCustomizer.java
vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/template/TestTemplate.java
vaadin-cdi-itest/src/test/java/com/vaadin/cdi/itest/RouteContextTest.java
vaadin-cdi/pom.xml
vaadin-cdi/src/test/java/com/vaadin/cdi/context/SessionUnderTestContext.java

Fixes #312
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/cdi/313)

Switch to Flow 3.0 

---

README.md
vaadin-cdi-itest/src/test/java/com/vaadin/cdi/itest/AbstractCdiTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/cdi/315)

Add 11.2 branch mention and add run ITs section

---

vaadin-cdi-itest/pom.xml

(cherry picked from commit 396c3b7c7552c1bc726f6a1c9c7c20f4facf8fa8)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/cdi/318)

Add apache-tomee:webprofile dependency to vaadin-cdi-itest

---

pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/cdi/321)

Add Repository definition to Pom

---

pom.xml
vaadin-cdi-itest/pom.xml
vaadin-cdi/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/cdi/322)

update flow version

---

pom.xml

this is related to platform ticket: vaadin/platform#794
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/cdi/323)

Update vaadin-parent to 2.0.2

---

vaadin-cdi-itest/pom.xml
vaadin-cdi-itest/src/test/java/com/vaadin/cdi/itest/ArchiveProvider.java

See #330
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/cdi/331)

Generate effective pom for JBoss shrinkwrap war packaging

---

pom.xml
vaadin-cdi-itest/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/cdi/332)

Enable vaadin-prerelease for snapshot

---

vaadin-cdi-itest/pom.xml
vaadin-cdi-itest/src/test/java/com/vaadin/cdi/itest/ArchiveProvider.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/cdi/333)

Generate effective pom for JBoss shrinkwrap war packaging (#331)

---

pom.xml
vaadin-cdi-itest/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/cdi/336)

Enable vaadin-prerelease for snapshot (#332)

---

vaadin-cdi-itest/pom.xml

Allow AppShell annotations on non-apshell classes to run CDI tests

---

vaadin-cdi-itest/pom.xml
vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/push/WebsocketPushView.java
vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/push/WebsocketXhrPushView.java

Use programmatic Push instead of declarative to avoid exception because of AppShell

---

vaadin-cdi/src/main/java/com/vaadin/cdi/CdiVaadinServletService.java
vaadin-cdi/src/test/java/com/vaadin/cdi/CdiVaadinServletServiceTest.java

Fixes #346.
In some special cases it is desirable to access the `Instantiator` instance via `VaadinService::getInstantiator` outside of the `VaadinServiceScoped` context, in which case access via CDI proxy will fail. This commit ensures that the actual contextual instance, instead of a CDI-provided proxy, is stored in `VaadinService`. Forgoing CDI indirection is acceptable since `VaadinService` and `Instantiator` are 1-1 (the former aggregates the latter) and share the same life cycle.

When creating the Instantiator instance for VaadinService, store the actual object instead of the CDI proxy

---

vaadin-cdi/src/main/java/com/vaadin/cdi/CdiVaadinServletService.java
vaadin-cdi/src/test/java/com/vaadin/cdi/CdiVaadinServletServiceTest.java

We may access VaadinService::getInstantiator without the VaadinServiceScoped context being active.
In this case, access of the Instantiator stored in VaadinService via proxy will fail. This change enables
access also in these cases. Foregoing CDI indirection is acceptable since VaadinService and Instantiator
are 1-1 and share the same life cycle.

CP: When creating the Instantiator instance for VaadinService, store the actual object instead of the CDI proxy (#347)

---

pom.xml
vaadin-cdi-itest/pom.xml
vaadin-cdi/pom.xml

Bump 13.0-SNAPSHOT version #8679

---

pom.xml
vaadin-cdi-itest/README.md
vaadin-cdi-itest/pom.xml
vaadin-cdi-itest/src/test/java/com/vaadin/cdi/itest/ArchiveProvider.java
vaadin-cdi/pom.xml

Test module is missing the polymer dependency

chore: Add missing polymer dependency

---

pom.xml
vaadin-cdi-itest/pom.xml
vaadin-cdi/pom.xml
vaadin-cdi/src/test/java/com/vaadin/cdi/CdiVaadinServletTest.java

Bump version to 14.0-SNAPSHOT

---

vaadin-cdi/src/test/java/com/vaadin/cdi/CdiVaadinServletTest.java

It is fine to use VaadinService instead of VaadinServletService.

chore: fix broken test to flow changes

---

vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/regression/RemoveOldContentView.java
vaadin-cdi-itest/src/test/java/com/vaadin/cdi/itest/RemoveOldContentTest.java

Regression test for #345 .
Related-to #10973

test: Remove old content of UI-scoped router layouts

---

vaadin-cdi/src/test/java/com/vaadin/cdi/CdiVaadinServletTest.java
vaadin-cdi/src/test/java/com/vaadin/cdi/TestCdiVaadinServletService.java

Please list all relevant dependencies in this section and provide summary of the change, motivation and context.
Fixes # (issue)

fix: avoid IllegalArgumentException in unit tests

---

.dtrack.yml

This enables Dependency-Track SCA analysis

chore: Add dtrack-maven-plugin configuration

---

vaadin-cdi/src/test/java/com/vaadin/cdi/CdiVaadinServletTest.java

Please list all relevant dependencies in this section and provide summary of the change, motivation and context.
Fixes # (issue)

test: fix mocking for changes in master

---

.dtrack.yml
pom.xml
vaadin-cdi-itest/pom.xml
vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/routecontext/CountedPerUI.java
vaadin-cdi/src/main/java/com/vaadin/cdi/context/RouteScopedContext.java
vaadin-cdi/src/test/java/com/vaadin/cdi/CdiVaadinServletTest.java
vaadin-cdi/src/test/java/com/vaadin/cdi/context/RouteContextualStorageManagerTest.java

cherrypicks from master

---

README.md
pom.xml
vaadin-cdi-itest/pom.xml
vaadin-cdi-itest/src/test/resources/arquillian.xml

Update wildfly and payara to
work with jdk11

test: update versions for wildfly and payara

---

vaadin-cdi-itest/pom.xml
vaadin-cdi/src/test/java/com/vaadin/cdi/TestCdiVaadinServletService.java

test: fix missing lookup mock

---

pom.xml
vaadin-cdi/src/main/java/com/vaadin/cdi/CdiVaadinServletService.java
vaadin-cdi/src/test/java/com/vaadin/cdi/CdiVaadinServletServiceTest.java
vaadin-cdi/src/test/java/com/vaadin/cdi/SerializationUtils.java
vaadin-cdi/src/test/java/com/vaadin/cdi/context/RouteContextNormalTest.java
vaadin-cdi/src/test/java/com/vaadin/cdi/context/RouteContextPseudoTest.java
vaadin-cdi/src/test/java/com/vaadin/cdi/context/SessionUnderTestContext.java

fix: fix serialization issues (#438)

---

README.md
vaadin-cdi-itest/src/test/java/com/vaadin/cdi/itest/PushTest.java

test: have push tests as not thread safe (#446)

---

vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/smoke/ProxiedNavigationTargetView.java
vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/smoke/UselessInterceptor.java
vaadin-cdi-itest/src/test/java/com/vaadin/cdi/itest/SmokeTest.java
vaadin-cdi/src/test/java/com/vaadin/cdi/CdiInstantiatorTest.java

Ensure changes in vaadin/flow#19151 works correctly on CDI

test: add test for proxied views

---

README.md
pom.xml
vaadin-cdi-itest/pom.xml
vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/invaliddeployment/NormalScopedLabel.java
vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/push/PushComponent.java
vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/routecontext/DetailApartView.java
vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/routecontext/DetailAssignedView.java
vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/routecontext/EventObserverLayout.java
vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/routecontext/EventView.java
vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/routecontext/MainLayout.java
vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/routecontext/MasterView.java
vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/routecontext/RootView.java
vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/sessioncontext/SessionContextView.java
vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/smoke/CdiView.java
vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/template/TestTemplate.java
vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/uicontext/UIContextRootView.java
vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/uicontext/UINormalScopedBeanView.java
vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/uicontext/UIScopedLabel.java
vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/uicontext/UIScopedView.java
vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/uievents/UIEventsView.java
vaadin-cdi/pom.xml
vaadin-cdi/src/test/java/com/vaadin/cdi/DeploymentValidatorTest.java
vaadin-cdi/src/test/java/com/vaadin/cdi/PolymerTest.java
vaadin-cdi/src/test/java/com/vaadin/cdi/context/UIUnderTestContext.java

Also updates to Vaadin 25.0 and JakartaEE 11

chore: bump project to 16.0

---

vaadin-cdi/src/test/java/com/vaadin/cdi/CdiVaadinServletServiceTest.java
vaadin-cdi/src/test/java/com/vaadin/cdi/TestCdiVaadinServletService.java

Fixes test errors caused by mocked VaadinSession
missing VaadinService to get access to deployment
configuration.

test: fix test errors

---

pom.xml
vaadin-cdi/src/test/java/com/vaadin/cdi/TestCdiVaadinServletService.java

Also bumps the Flow version to 23.6

test: fix VaadinService test mock (14.1)
