- vaadin-cdi/src/test/java/com/vaadin/cdi/shiro/GuestView.java
- vaadin-cdi/src/test/java/com/vaadin/cdi/shiro/LoginPane.java
- vaadin-cdi/src/test/java/com/vaadin/cdi/shiro/ShiroTest.java
The test worked fine on firefox, and chrome, but failed on phantomjs. 
Upgrading phantomjsdriver to 1.3.0 does not help.
Workaround was to change LoginPane, and enclosing view to full-Sized. 
Related issue #186 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/cdi/192)
> fix ignored ShiroTest

- vaadin-cdi/src/main/java/com/vaadin/cdi/server/VaadinCDIServletService.java
The workaround in this patch caused Payara and Glassfish servers to fail.
This reverts commit de2983e28de33623d673a01009deec99f64be8be.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/cdi/218)
> Revert "Tomcat DeltaManager session replication workaround"

- vaadin-cdi/src/main/java/com/vaadin/cdi/CDIViewProvider.java
Addresses #98
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/cdi/219)
> Change visibility of getViewBean and parseViewName to protected

- vaadin-cdi/src/main/java/com/vaadin/cdi/CDIUIProvider.java
With a deployment path of `http://example.com/Context/`, and a UI mapped to "" or "/*", navigating to `page1` would result in `http://example.com/page1` rather than `http://example.com/Context/page1`.
Instead, include the context path in uiRootPath.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/cdi/241)
> Fix push state nav with non-empty context path and empty ui mapping

- pom.xml
- vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/invaliddeployment/DeploymentView.java
- vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/invaliddeployment/NormalScopedLabel.java
- vaadin-cdi-itest/src/test/java/com/vaadin/cdi/itest/InvalidDeploymentTest.java
- vaadin-cdi/pom.xml
- vaadin-cdi/src/main/java/com/vaadin/cdi/DeploymentValidator.java
- vaadin-cdi/src/main/java/com/vaadin/cdi/VaadinExtension.java
- vaadin-cdi/src/test/java/com/vaadin/cdi/CdiInstantiatorTest.java
- vaadin-cdi/src/test/java/com/vaadin/cdi/DeploymentValidatorTest.java
- vaadin-cdi/src/test/java/com/vaadin/cdi/JavaSPIVaadinServiceInitListener.java
- vaadin-cdi/src/test/java/com/vaadin/cdi/PolymerTest.java
- vaadin-cdi/src/test/java/com/vaadin/cdi/TestDeploymentValidator.java
- vaadin-cdi/src/test/java/com/vaadin/cdi/context/UIUnderTestContext.java
- vaadin-cdi/src/test/resources/META-INF/beans.xml
- vaadin-cdi/src/test/resources/META-INF/services/com.vaadin.flow.server.VaadinServiceInitListener
- vaadin-cdi/src/test/resources/com/vaadin/cdi/test-template.html
Any normal scoped CDI bean with a component type breaks deployment.
Contains unit test for polymer template field injection, and a case when a normal scoped component does not work.
Test for CdiInstantiator also included. Not affected, it is just missed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/cdi/253)
> Deployment validation for normal scoped components

- vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/routecontext/AbstractCountedBean.java
- vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/routecontext/AbstractCountedView.java
- vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/routecontext/ApartBean.java
- vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/routecontext/AssignedBean.java
- vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/routecontext/CountedPerUI.java
- vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/routecontext/DetailApartView.java
- vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/routecontext/DetailAssignedView.java
- vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/routecontext/ErrorHandlerView.java
- vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/routecontext/ErrorParentView.java
- vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/routecontext/ErrorView.java
- vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/routecontext/EventView.java
- vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/routecontext/MasterView.java
- vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/routecontext/PostponeView.java
- vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/routecontext/RerouteView.java
- vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/routecontext/RootView.java
- vaadin-cdi-itest/src/test/java/com/vaadin/cdi/itest/RouteContextTest.java
- vaadin-cdi/src/main/java/com/vaadin/cdi/VaadinExtension.java
- vaadin-cdi/src/main/java/com/vaadin/cdi/annotation/NormalRouteScoped.java
- vaadin-cdi/src/main/java/com/vaadin/cdi/annotation/RouteScopeOwner.java
- vaadin-cdi/src/main/java/com/vaadin/cdi/annotation/RouteScoped.java
- vaadin-cdi/src/main/java/com/vaadin/cdi/context/AbstractContextualStorageManager.java
- vaadin-cdi/src/main/java/com/vaadin/cdi/context/RouteScopedContext.java
- vaadin-cdi/src/test/java/com/vaadin/cdi/context/RouteContextNormalTest.java
- vaadin-cdi/src/test/java/com/vaadin/cdi/context/RouteContextPseudoTest.java
- vaadin-cdi/src/test/java/com/vaadin/cdi/context/RouteContextualStorageManagerTest.java
Implementation of ```@RouteScoped```, and ```@NormalRouteScoped``` contexts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/cdi/256)
> Introduce @RouteScoped context

- vaadin-cdi/src/main/java/com/vaadin/cdi/DeploymentValidator.java
- vaadin-cdi/src/test/java/com/vaadin/cdi/DeploymentValidatorTest.java
- vaadin-cdi/src/test/java/com/vaadin/cdi/TestDeploymentValidator.java
Some basic validation of ```@RouteScopeOwner```
- ```@RouteScopeOwner``` value have to be a route component
- A bean qualified by ```@RouteScopeOwner``` have to be ```@RouteScoped``` or ```@NormalRouteScoped```
- ```@RouteScopeOwner``` is mandatory on a ```@RouteScoped``` or ```@NormalRouteScoped``` non route component
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/cdi/257)
> Deployment validation for route scoped context

- pom.xml
- vaadin-cdi-itest/pom.xml
- vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/push/PushComponent.java
- vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/push/WebsocketPushView.java
- vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/push/WebsocketXhrPushView.java
- vaadin-cdi-itest/src/test/java/com/vaadin/cdi/itest/PushTest.java
Testing wich CDI contexts are active from a foreground ( event handler ) thread, and from a background thread.
The goal was to test how CDI and websocket works together.
Tested transport modes are `WEBSOCKET_XHR`, and `WEBSOCKET`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/cdi/259)
> Integration test to show push behaviour

- pom.xml
- vaadin-cdi-itest/pom.xml
- vaadin-cdi/pom.xml
We do this for other projects, plus, due to SemVer, since Flow version was bumped to a new major, we need to bump the plugin's major either.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/cdi/290)
> Bump the major version

- vaadin-cdi/src/main/java/com/vaadin/cdi/CdiVaadinServletService.java
- vaadin-cdi/src/test/java/com/vaadin/cdi/CdiVaadinServletServiceTest.java
Adopted original PR in master (11.2) to report from servlet service instead of instantiator since the latter could be overridden in 11.0.
Should have maybe done the same for the original PR in master, but this should be fine.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/cdi/308)
> Cherry-pick: Add usage statistics

- vaadin-cdi-itest/pom.xml
It should fix the error in SNAPSHOT build. See [the build log](https://bender.vaadin.com/viewLog.html?buildId=118043&buildTypeId=Flow_AddOns_FlowCdi22).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/cdi/317)
> Add apache-tomee:webprofile dependency to vaadin-cdi-itest

- vaadin-cdi-itest/pom.xml
Previous version 7.0.4 had issues with the recently added flow-server dependency com.fasterxml.jackson.datatype:jackson-datatype-jsr310.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/cdi/329)
> Upgrade TomEE to version 7.0.7

- vaadin-cdi-itest/pom.xml
- vaadin-cdi-itest/src/test/java/com/vaadin/cdi/itest/ArchiveProvider.java
When packaging war for IT, JBoss shrinkwrap got dependencies from `vaadin-cdi-itest/pom.xml`. This loaded the wrong version when running Maven with property override affecting Flow version (`vaadin.flow.version`). Added a step that generates the effective pom and use that in IT.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/cdi/330)
> Generate effective pom for JBoss shrinkwrap war packaging

- pom.xml
Fix failing build of CDI 10.0 for Flow 1.0 with Chrome 80+
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/cdi/340)
> Pin webcomponentsjs version to 1.2.2

- pom.xml
As the master Flow is at `5.0-SNAPSHOT`, this change updates the version in `pom.xml` accordingly.
> chore: Update Flow version to 5.0-SNAPSHOT

- vaadin-cdi/src/test/java/com/vaadin/cdi/CdiVaadinServletTest.java
Adds necessary mocking for application configuration for CdiServlet
in unit tests.
Related to vaadin/flow#9642
> refactor: fix unit tests after app-config changes

- pom.xml
- vaadin-cdi-itest/pom.xml
- vaadin-cdi/pom.xml
13.0 will be used to build on top of Flow 8.0 and target Vaadin 21.
Version 12.0 is compatible for Vaadin 15-20.
> chore: downgrade version to 13.0-SNAPSHOT

- vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/routecontext/AbstractCountedView.java
- vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/routecontext/BeanNoOwner.java
- vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/routecontext/ChildNoOwnerView.java
- vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/routecontext/CustomException.java
- vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/routecontext/CustomExceptionSubButton.java
- vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/routecontext/CustomExceptionSubDiv.java
- vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/routecontext/ErrorHandlerView.java
- vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/routecontext/ErrorParentView.java
- vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/routecontext/InvalidView.java
- vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/routecontext/MainLayout.java
- vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/routecontext/MasterView.java
- vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/routecontext/ParentNoOwnerView.java
- vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/routecontext/PreserveOnRefreshBean.java
- vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/routecontext/PreserveOnRefreshView.java
- vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/routecontext/RootView.java
- vaadin-cdi-itest/src/test/java/com/vaadin/cdi/itest/RouteContextTest.java
- vaadin-cdi/src/main/java/com/vaadin/cdi/DeploymentValidator.java
- vaadin-cdi/src/main/java/com/vaadin/cdi/annotation/RouteScoped.java
- vaadin-cdi/src/main/java/com/vaadin/cdi/context/AbstractContextualStorageManager.java
- vaadin-cdi/src/main/java/com/vaadin/cdi/context/RouteScopedContext.java
- vaadin-cdi/src/test/java/com/vaadin/cdi/DeploymentValidatorTest.java
- vaadin-cdi/src/test/java/com/vaadin/cdi/context/AbstractContextTest.java
- vaadin-cdi/src/test/java/com/vaadin/cdi/context/RouteContextNormalTest.java
- vaadin-cdi/src/test/java/com/vaadin/cdi/context/RouteContextPseudoTest.java
- vaadin-cdi/src/test/java/com/vaadin/cdi/context/RouteContextualStorageManagerTest.java
- vaadin-cdi/src/test/java/com/vaadin/cdi/context/SessionUnderTestContext.java
- vaadin-cdi/src/test/java/com/vaadin/cdi/context/TestNavigationTarget.java
- vaadin-cdi/src/test/java/com/vaadin/cdi/context/UIUnderTestContext.java
- presere beans for PreserveOnRefresh views
- reimplement absent RouteScopeOwner semantic
- do not allow to use (route) scope when it's not available
fixes #369
Please list all relevant dependencies in this section and provide summary of the change, motivation and context.
Fixes # (issue)
> feat: reimplement @RouteScoped to keep beans for PreserveOnRefresh

- vaadin-cdi/src/main/java/com/vaadin/cdi/context/RouteScopedContext.java
- vaadin-cdi/src/test/java/com/vaadin/cdi/context/RouteContextualStorageManagerTest.java
If bean creation is not requested, just return a null value from context storage
instead of throwing an exception because route owner instance is not available
in current navigation components chain
Fixes #390
> fix: throw on not existing scope only if bean creation is requested

- vaadin-cdi/src/main/java/com/vaadin/cdi/CdiServletDeployer.java
When using Vite, DevModeInitializer blocks dev-server startup until a VaadinServlet is deployed because it needs to get the servlet path to use. If the container lazily loads servlets, Vite will not start until the first HTTP request for the Vaadin servlet is received.
This change sets load-on-startup feature for automatically deployed Vaadin servlet, to ensure that the servlet and Vite are loaded on the startup of the Web application
Part of vaadin/flow#14479
> fix: set load-on-startup for automatically registered Vaadin servlet

- vaadin-cdi/src/test/java/com/vaadin/cdi/CdiVaadinServletTest.java
Fixes CdíVaadinServletTest which broke due to  https://github.com/vaadin/flow/pull/15188 which assumes that vaadin servlet has been registered when Atmosphere is being initialized
> test: Fixes CdiVaadinServletTest, broken due to missing servlet registration

- pom.xml
- vaadin-cdi/src/test/java/com/vaadin/cdi/CdiVaadinServletTest.java
Fixes CdíVaadinServletTest which broke due to vaadin/flow#15188 which assumes that vaadin servlet has been registered when Atmosphere is being initialized
(cherry picked from commit 7c29686a4b3e29b78b3af7293887155286e9971d)
> test: Fixes CdiVaadinServletTest, broken due to missing servlet registration (#420)

- vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/routecontext/EventObserverLayout.java
- vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/routecontext/LayoutEventView.java
- vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/routecontext/LayoutEventView2.java
- vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/routecontext/RootView.java
- vaadin-cdi-itest/src/test/java/com/vaadin/cdi/itest/RouteContextTest.java
- vaadin-cdi/src/main/java/com/vaadin/cdi/context/RouteScopedContext.java
When changing routes where a RouterLayout comes into play that has a RoutePrefix associated with it and where this routerlayout is annotated to be @RouteScoped the spec has changed between Vaadin CDI 12 and Vaadin CDI 13 so that strictly the @RouteScopeOwner is considered to be the innermost Route component. This broke our code where we were depending on the fact that these RouterLayouts would not be recreated. We had defined services which were RouteScoped and had a RouterLayout as RouteScopeOwner but this did not work anymore.
This proposed change will result in RouterLayouts of this kind to be considered to have themselves as  @RouteScopeOwner. This fits with the notion that the Route part which pertains to this RouterLayout does in fact not change.
So imagine a component A with Route …
> feat: Retain routescoped parentlayouts on route change

- vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/routecontext/EventObserverLayout.java
- vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/routecontext/LayoutEventView.java
- vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/routecontext/LayoutEventView2.java
- vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/routecontext/RootView.java
- vaadin-cdi-itest/src/test/java/com/vaadin/cdi/itest/RouteContextTest.java
- vaadin-cdi/src/main/java/com/vaadin/cdi/context/RouteScopedContext.java
When changing routes where a RouterLayout comes into play that has a RoutePrefix associated with it and where this routerlayout is annotated to be @RouteScoped the spec has changed between Vaadin CDI 12 and Vaadin CDI 13 so that strictly the RouteScopeOwner is considered to be the innermost Route component.
This change will result in RouterLayouts of this kind to have a RouteScopeOwner which will be themselves. This fits with the notion that the Route part which pertains to this RouterLayout does in fact not change.
> feat: Retain routescoped parentlayouts on route change (#394) (CP: 14.1)

- vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/instantiatorcustomize/InstantiatorAlternative.java
- vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/instantiatorcustomize/InstantiatorFactoryAlternative.java
- vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/instantiatorcustomize/InstantiatorFactoryDecorator.java
- vaadin-cdi-itest/src/test/java/com/vaadin/cdi/itest/InstantiatorFactoryCustomizeTest.java
- vaadin-cdi-itest/src/test/java/com/vaadin/cdi/itest/InvalidDeploymentTest.java
- vaadin-cdi/src/main/java/com/vaadin/cdi/AbstractCdiInstantiator.java
- vaadin-cdi/src/main/java/com/vaadin/cdi/CdiInstantiator.java
- vaadin-cdi/src/main/java/com/vaadin/cdi/CdiInstantiatorFactory.java
- vaadin-cdi/src/main/java/com/vaadin/cdi/CdiVaadinServletService.java
- vaadin-cdi/src/test/java/com/vaadin/cdi/CdiInstantiatorTest.java
- vaadin-cdi/src/test/java/com/vaadin/cdi/CdiVaadinServletServiceTest.java
Changes related to Flow 24 deprecated code removal https://github.com/vaadin/flow/issues/15665
> refactor!: Instantiator.init() replaced with InstantiatorFactory

- pom.xml
DeltaSpike snapshot is not used anymore, so no need for a snapshot repo.
> chore: Remove not needed apache snapshot repo

- vaadin-cdi-itest/pom.xml
The version in use has issues with ASM.
The problem can be fix upgrading tomee to the latest 7.1.x, that however is EOL, or to to 8.0.x
> test: upgrade tomee to 8.x

- vaadin-cdi-itest/pom.xml
With Payara 4 there are conflicts with JNA lib provided by the license checker.
Upgrade to Payara 5 fixes the validation build
> test: upgrade payara to 5.x

- pom.xml
- vaadin-cdi/pom.xml
- vaadin-cdi/src/main/java/com/vaadin/cdi/CdiVaadinServletService.java
- vaadin-cdi/src/main/java/com/vaadin/cdi/context/RouteScopedContext.java
- vaadin-cdi/src/test/java/com/vaadin/cdi/CdiVaadinServletServiceTest.java
- vaadin-cdi/src/test/java/com/vaadin/cdi/SerializationUtils.java
- vaadin-cdi/src/test/java/com/vaadin/cdi/context/RouteContextNormalTest.java
- vaadin-cdi/src/test/java/com/vaadin/cdi/context/RouteContextPseudoTest.java
Fixes serialization issues
Fixes #436
Fixes #437
> fix: fix serialization issues

- pom.xml
- vaadin-cdi/src/main/java/com/vaadin/cdi/CdiVaadinServletService.java
- vaadin-cdi/src/main/java/com/vaadin/cdi/context/RouteScopedContext.java
- vaadin-cdi/src/test/java/com/vaadin/cdi/CdiVaadinServletServiceTest.java
- vaadin-cdi/src/test/java/com/vaadin/cdi/SerializationUtils.java
- vaadin-cdi/src/test/java/com/vaadin/cdi/context/RouteContextNormalTest.java
- vaadin-cdi/src/test/java/com/vaadin/cdi/context/RouteContextPseudoTest.java
> fix: fix serialization issues (#438)

- vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/push/PushComponent.java
Schedule the background thread that applies changes to the UI to start after the click listener request has completed, to ensure the changes are applied in the background thread and not in the request thread.
Fixes #445
> test: delay start of background thread

- vaadin-cdi-itest/src/test/java/com/vaadin/cdi/itest/ArchiveProvider.java
Resolving dependency one by one may cause failures if artifacts have transitive dependency to other libraries but in different versions. In this case, resolution fails because the resolver is working offline, but only the winning dependency from effective pom is actually downloaded on CI server.
For example, if flow-server has a transitive dependency to library X at version 1 and flow-polymer-template defines it at version 2, then version 2 is downloaded. However, when resolving flow-server alone the resolver wants to download version 1 since it has no knowledge of version 2, but version 1 potentially has not been previously downloaded. Resolving all dependencies together resolves the issue, since the correct version of the transitive dependencies are computed.
> test: resolve web archive dependencies all together

- vaadin-cdi/src/main/java/com/vaadin/cdi/AbstractCdiInstantiator.java
- vaadin-cdi/src/test/java/com/vaadin/cdi/CdiInstantiatorDefaultsTest.java
- vaadin-cdi/src/test/java/com/vaadin/cdi/CdiInstantiatorTest.java
A MenuAccessControl instance is required when operating with MenuConfiguration. This change provides a default implementation if the user project does not define a specialized bean.
> fix: provide default MenuAccessControl instance

- vaadin-cdi-itest/src/test/java/com/vaadin/cdi/itest/ServiceTest.java
Flow client introduced a little delay in session expiration handling to prevent issues with slow connections.
This change makes the test wait for notification to be shown before asserting on text message.
> test: wait for system messages notification

- vaadin-cdi-itest/pom.xml
- vaadin-cdi-itest/src/test/resources/liberty/server.xml
- vaadin-cdi/pom.xml
- vaadin-cdi/src/main/java/com/vaadin/cdi/CdiVaadinServletService.java
- vaadin-cdi/src/main/java/com/vaadin/cdi/VaadinExtension.java
- vaadin-cdi/src/main/java/com/vaadin/cdi/VaadinTaskExecutorSelector.java
- vaadin-cdi/src/test/java/com/vaadin/cdi/CdiVaadinServletServiceExecutorTest.java
Enhances CDI VaadinService implementation trying to detect the best Executor option available on the container. It first looks for an Executor bean annotated with `@VaadinServiceEnabled` and then falls back to the container ManagedExecutorService.
Closes #468
> feat: detect specific Executor for VaadinService

- vaadin-cdi-itest/pom.xml
- vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/push/CustomSchedulerPushComponent.java
- vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/push/ManagedExecutorPushComponent.java
- vaadin-cdi-itest/src/main/java/com/vaadin/cdi/itest/push/PushComponent.java
- vaadin-cdi-itest/src/test/java/com/vaadin/cdi/itest/ArchiveProvider.java
- vaadin-cdi-itest/src/test/java/com/vaadin/cdi/itest/NeedsCDICompliantContainer.java
- vaadin-cdi-itest/src/test/java/com/vaadin/cdi/itest/PushTest.java
- vaadin-cdi-itest/src/test/java/com/vaadin/cdi/itest/PushWithoutManagedExecutorTest.java
- vaadin-cdi-itest/src/test/resources/arquillian.xml
- vaadin-cdi-itest/src/test/resources/tomcat/tomcat-users.xml
- vaadin-cdi/src/main/java/com/vaadin/cdi/VaadinTaskExecutorSelector.java
- vaadin-cdi/src/test/java/com/vaadin/cdi/CdiVaadinServletServiceExecutorTest.java
This change provides a solution for environments that aren't fully Jakarta EE
compliant (e.g., Tomcat with Weld) by implementing a runtime check for
ManagedExecutorService availability. This prevents deployment failures by:
1. Programmatically resolving the bean through CDI
2. Gracefully handling missing ManagedExecutorService in the classpath
3. Handling javax.naming.NameNotFoundException when JNDI lookup fails
The implementation allows for fallback to alternative execution strategies
when necessary, improving application resilience.
Also adds tests for non-CDI compliant environment scenarios.
Fixes #476
> fix: prevent startup failures on non-Jakarta EE compliant environments
